services:
  - type: web
    name: airport-map-api
    runtime: docker
    plan: free
    branch: main
    rootDir: Back-End
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/locations
    autoDeployTrigger: commit
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://aeroproce.aeroproce.workers.dev
