-- Run once on an empty database. Creates the final relational schema directly.
BEGIN;
CREATE TABLE terminals (
    code TEXT PRIMARY KEY CHECK (btrim(code) <> ''),
    name TEXT NOT NULL
);
CREATE TABLE floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminal_code TEXT NOT NULL REFERENCES terminals(code),
    level INTEGER NOT NULL,
    name TEXT NOT NULL,
    UNIQUE (terminal_code, level)
);
CREATE TABLE location_types (
    code TEXT PRIMARY KEY CHECK (btrim(code) <> ''),
    name TEXT NOT NULL
);
CREATE TABLE facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> '')
);
CREATE SEQUENCE location_id_seq;
CREATE TABLE locations (
    id BIGINT PRIMARY KEY DEFAULT nextval('location_id_seq'),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    floor_id BIGINT NOT NULL REFERENCES floors(id),
    type_code TEXT REFERENCES location_types(code),
    x DOUBLE PRECISION, y DOUBLE PRECISION,
    lat DOUBLE PRECISION, lng DOUBLE PRECISION,
    source_id BIGINT,
    phone TEXT, website TEXT, area TEXT, description TEXT,
    opening_hours TEXT,
    facilities_known BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT location_coordinates CHECK ((x IS NOT NULL AND y IS NOT NULL) OR (lat IS NOT NULL AND lng IS NOT NULL))
);
ALTER SEQUENCE location_id_seq OWNED BY locations.id;
COMMENT ON COLUMN locations.x IS 'SVG pixel X, not longitude';
COMMENT ON COLUMN locations.y IS 'SVG pixel Y, not latitude';
COMMENT ON COLUMN locations.lat IS 'WGS84 latitude';
COMMENT ON COLUMN locations.lng IS 'WGS84 longitude';
CREATE TABLE location_facilities (
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    facility_id BIGINT NOT NULL REFERENCES facilities(id),
    position INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (location_id, facility_id),
    UNIQUE (location_id, position)
);
CREATE INDEX locations_floor_idx ON locations(floor_id);
CREATE INDEX locations_type_idx ON locations(type_code);
CREATE INDEX location_facilities_facility_idx ON location_facilities(facility_id);
COMMIT;
