CREATE TABLE terminals (
    code TEXT PRIMARY KEY CHECK (btrim(code) <> ''),
    name TEXT NOT NULL
);
CREATE TABLE floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminal_code TEXT NOT NULL REFERENCES terminals(code),
    level INTEGER NOT NULL,
    name TEXT NOT NULL,
    UNIQUE (terminal_code, level)
);
CREATE TABLE location_types (
    code TEXT PRIMARY KEY CHECK (btrim(code) <> ''),
    name TEXT NOT NULL
);
CREATE TABLE facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> '')
);
INSERT INTO terminals(code, name)
SELECT DISTINCT terminal, CASE terminal WHEN 'T1' THEN 'Ga Nội địa T1'
 WHEN 'T2' THEN 'Ga Quốc tế T2' WHEN 'T3' THEN 'Ga Nội địa T3'
 WHEN 'SGN_CAMPUS' THEN 'Khuôn viên sân bay' ELSE terminal END FROM locations;
INSERT INTO floors(terminal_code, level, name)
SELECT DISTINCT terminal, floor, CASE WHEN floor = 0 THEN 'Tầng trệt' ELSE 'Tầng ' || floor END FROM locations;
INSERT INTO location_types(code, name) SELECT DISTINCT type, type FROM locations WHERE type IS NOT NULL;
ALTER TABLE locations ADD COLUMN floor_id BIGINT REFERENCES floors(id);
ALTER TABLE locations ADD COLUMN type_code TEXT REFERENCES location_types(code);
-- Preserve the API distinction between null facilities and an explicitly empty list.
ALTER TABLE locations ADD COLUMN facilities_known BOOLEAN NOT NULL DEFAULT false;
UPDATE locations l SET floor_id = f.id FROM floors f WHERE f.terminal_code = l.terminal AND f.level = l.floor;
UPDATE locations SET type_code = type, facilities_known = facilities IS NOT NULL;
ALTER TABLE locations ALTER COLUMN floor_id SET NOT NULL;
CREATE TABLE location_facilities (
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    facility_id BIGINT NOT NULL REFERENCES facilities(id),
    position INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (location_id, facility_id),
    UNIQUE (location_id, position)
);
INSERT INTO facilities(name)
SELECT DISTINCT value FROM locations l CROSS JOIN LATERAL jsonb_array_elements_text(l.facilities::jsonb) e(value);
INSERT INTO location_facilities(location_id, facility_id, position)
SELECT l.id, f.id, (e.ordinality - 1)::integer FROM locations l
 CROSS JOIN LATERAL jsonb_array_elements_text(l.facilities::jsonb) WITH ORDINALITY e(value, ordinality)
 JOIN facilities f ON f.name = e.value;
DROP INDEX locations_terminal_floor_idx;
ALTER TABLE locations DROP COLUMN terminal, DROP COLUMN floor, DROP COLUMN type, DROP COLUMN facilities;
CREATE INDEX locations_floor_idx ON locations(floor_id);
CREATE INDEX locations_type_idx ON locations(type_code);
CREATE INDEX location_facilities_facility_idx ON location_facilities(facility_id);
